server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    kubernetes:
      enabled: true

endpoint:
  configuration:
    cryptoService: http://crypto-service/
    trustChainService: http://trust-chain-service/
    tenantManagementService: http://tenant-management-service