server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

routeLocator:
  uriPrefix: http://

eureka:
  client:
    enabled: false