server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
    kubernetes:
      enabled: false

endpoint:
  configuration:
    cryptoService: http://localhost:8083
    trustChainService: http://localhost:8084
    tenantManagementService: http://localhost:8085
    authService: http://localhost:8086

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true

okta:
  issuerUrl: https://dev-52177607.okta.com/oauth2/default
  audience: api://default
  connectionTimeout: 5s