---
apiVersion: v1
kind: Secret
metadata:
  name: opabs-db-creds
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ext-service
spec:
  clusterIP: None
  ports:
    - port: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-ext-service
subsets:
  - addresses:
      - ip: 192.168.0.128
    ports:
      - port: 5432