apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-chain-service
  labels:
    app: trust-chain-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trust-chain-service
  template:
    metadata:
      labels:
        app: trust-chain-service
    spec:
      containers:
        - name: trust-chain-service
          image: prithuadhikary/trust-chain-service:1.0
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: DB_HOST
              value: postgres-ext-service
            - name: DB_NAME
              value: opabs
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: opabs-db-creds
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: opabs-db-creds
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trust-chain-service
spec:
  type: ClusterIP
  selector:
    app: trust-chain-service
  ports:
    - port: 80
      targetPort: 80
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: crypto-management-service
#  annotations:
#    kubernetes.io/ingress.class: haproxy
#spec:
#  rules:
#    - http:
#        paths:
#          - backend:
#              service:
#                name: crypto-management-service
#                port:
#                  number: 80
#            pathType: Prefix
#            path: /api