
server:
  port: 8085
  servlet:
    context-path: /api/tenant-management-service

spring:
  cloud:
    kubernetes:
      enabled: false
  security:
    filter:
      order: 10   # this makes space for 10 custom spring security filters.