spring:
  application:
    name: trust-chain-service
  cloud:
    kubernetes:
      discovery:
        enabled: false
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/opabs?currentSchema=trust_chain
    username: postgres
    password: password


server:
  port: 8084
  servlet:
    context-path: /api/trust-chain-service

