apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: opabs-web-deployment
  name: opabs-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opabs-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opabs-web
    spec:
      containers:
      - image: prithuadhikary/opabs-web:latest
        name: opabs-web
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: opabs-web
  name: opabs-web
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: opabs-web
status:
  loadBalancer: {}